### ISSUE TITLE
Crash opening GUI on MC 1.12.2, RFLux 1.12-0.2.0, MCJty 1.12-2.6.2

### ISSUE THREAD

**Issue by ChronosWS** [romelo333/rflux#3]
https://pastebin.com/sSMGUWBt

Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mcjty.lib.gui.WindowManager.addWindow(WindowManager.java:56)
	at mcjty.lib.container.GenericGuiContainer.getWindowManager(GenericGuiContainer.java:93)
	at mcjty.lib.container.GenericGuiContainer.drawWindow(GenericGuiContainer.java:254)
	at romelo333.rflux.blocks.GuiLight.func_146976_a(GuiLight.java:112)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at mcjty.lib.container.GenericGuiContainer.func_73863_a(GenericGuiContainer.java:259)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:366)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Right click on a Light Block (on), in Creative.  There are many other mods on this server but they don't appear to be involved in this crash.  I looked at the other issue which appeared to be resolved by updating the Redstone Flux lib, but mine is already updated to 1.12-2.0.1.2.

**Comment by marcin212** [comment]
```
Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(SourceFile:47)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at mcjty.lib.container.GenericBlock.createClientGui(GenericBlock.java:516)
	at romelo333.rflux.GuiProxy.getClientGuiElement(GuiProxy.java:31)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:279)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50)
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43)
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler$$Lambda$2321/118346754.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at mcjty.lib.container.GenericBlock.createClientGui(GenericBlock.java:512)
	... 19 more
Caused by: java.lang.NoSuchMethodError: romelo333.rflux.blocks.LightTE.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I
	at romelo333.rflux.blocks.GuiLight.<init>(GuiLight.java:47)
	... 24 more
```
